# Generated by Django 5.2.12 on 2026-06-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
